name: Call a reusable workflow with matrix value

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable.yaml
    strategy:
      matrix:
        sound: [ "foo", "buzz" ]
    with:
      value: ${{ matrix.sound }}
